CREATE TABLE IF NOT EXISTS `wechat_group_member_profiles` (
  `room_id` varchar(128) NOT NULL,
  `member_wxid` varchar(128) NOT NULL,
  `nickname` varchar(255) NOT NULL DEFAULT '',
  `display_name` varchar(255) DEFAULT NULL,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(255) NOT NULL DEFAULT '',
  `sex` int DEFAULT NULL,
  `country` varchar(128) NOT NULL DEFAULT '',
  `province` varchar(128) NOT NULL DEFAULT '',
  `city` varchar(128) NOT NULL DEFAULT '',
  `signature` text,
  `big_head_img_url` text,
  `small_head_img_url` text,
  `head_img_md5` varchar(128) NOT NULL DEFAULT '',
  `chatroom_member_flag` int DEFAULT NULL,
  `status` int DEFAULT NULL,
  `inviter_user_name` varchar(128) NOT NULL DEFAULT '',
  `add_chatroom_scene_xml` text,
  `is_in_chat_room` boolean DEFAULT NULL,
  `last_seen_message_at` double DEFAULT NULL,
  `group_info_synced_at` datetime DEFAULT NULL,
  `profile_synced_at` datetime DEFAULT NULL,
  `profile_sync_error` text,
  `raw_profile_json` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_id`, `member_wxid`),
  KEY `idx_room_profile_synced_at` (`room_id`, `profile_synced_at`),
  KEY `idx_room_last_seen_message_at` (`room_id`, `last_seen_message_at`),
  KEY `idx_alias` (`alias`),
  KEY `idx_nickname` (`nickname`),
  KEY `idx_display_name` (`display_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wechat_group_member_profile_sync_state` (
  `room_id` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'idle',
  `sync_type` varchar(32) NOT NULL DEFAULT 'incremental',
  `cursor_member_wxid` varchar(128) NOT NULL DEFAULT '',
  `last_full_synced_at` datetime DEFAULT NULL,
  `last_incremental_synced_at` datetime DEFAULT NULL,
  `processed_count` int NOT NULL DEFAULT 0,
  `failed_count` int NOT NULL DEFAULT 0,
  `last_error` text,
  `locked_until` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_id`),
  KEY `idx_status_locked_until` (`status`, `locked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
